### ISSUE TITLE
bug: build errors

### ISSUE THREAD

**Issue by Bajeclyv** [TNtube/Cardia#43]
I got a warning while building the project with XMake:
```xmake
warning: .\xmake.lua:109: includedir 'Tests\Cardia\include' not found
```
Since it's a warning, I say "it's fine, I'll just launch the engine and see what it does". So I run the command `xmake run CardiaTor`, and...
```output
available extensions:
        VK_KHR_device_group_creation
        VK_KHR_display
        VK_KHR_external_fence_capabilities
        VK_KHR_external_memory_capabilities
        VK_KHR_external_semaphore_capabilities
        VK_KHR_get_display_properties2
        VK_KHR_get_physical_device_properties2
        VK_KHR_get_surface_capabilities2
        VK_KHR_surface
        VK_KHR_surface_protected_capabilities
        VK_KHR_win32_surface
        VK_EXT_debug_report
        VK_EXT_debug_utils
        VK_EXT_direct_mode_display
        VK_EXT_swapchain_colorspace
        VK_NV_external_memory_capabilities
        VK_KHR_portability_enumeration
        VK_LUNARG_direct_driver_loading
required extensions:
        VK_KHR_surface
        VK_KHR_win32_surface
Device count: 1
physical device: NVIDIA GeForce RTX 3050
Present mode: V-Sync
error: execv(C:\Users\Fulbion\source\repos\Cardia\build\release-windows-x64\CardiaTor\bin\CardiaTor.exe ) failed(-1073740791)
```
The app gets pitch white for a couple of seconds, and it crashes. What's wrong then?

**Comment by TNtube** [comment]
Hi, thanks for the issue. There is some requirements that I still have to write on the readme, but the engine depends on python 3.11 actually. You'll need to have it in the PATH, and also build and install cardia.py (using python -m build and pip install the output file).

If you done all of this and still have the same issue, keep me updated

**Comment by Bajeclyv** [comment]
Should've warned you earlier, but I got the same problem even after doing all of these steps. I've got already Python 3.11.3, and I had no errors building `cardia.py`. But, there is exactly the same error on launch. Is it because of my Vulkan installation?

**Comment by TNtube** [comment]
Shaders needed to be compiled.
